name: uplift_app
description: A job search application with AI recommendations
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  cached_network_image: ^3.3.1
  intl: ^0.20.2
  url_launcher: ^6.2.2
  image_picker: ^0.8.7      # picking images and videos
  file_picker: ^5.2.6       # Alternative for file selection
  video_player: ^2.6.0      # playing videos
  chewie: ^1.4.0            # better video player UI
  carousel_slider: ^4.2.1   # image gallery
  uuid: ^3.0.7              # generating unique filenames
  path: ^1.8.3   
  
  # Updated Supabase packages
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.1.0
  
  # Add these to resolve sign_in_with_apple issues
  sign_in_with_apple: ^6.1.4
  sign_in_with_apple_web: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env